# Generated by Django 5.1.3 on 2024-11-05 14:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('bookId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=50)),
                ('bookAuthor', models.CharField(max_length=50)),
                ('bookPrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bookStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardId', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 8', regex='^.{8}$')])),
                ('cardBalance', models.FloatField(default=0)),
                ('cardStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('goodsId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goodsName', models.CharField(max_length=50)),
                ('goodsPrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('goodsAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('userType', models.CharField(choices=[('admin', '管理员'), ('student', '学生'), ('staff', '教师')], max_length=50)),
                ('lastLogin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='billLog',
            fields=[
                ('billId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billType', models.CharField(max_length=50)),
                ('billAmount', models.FloatField()),
                ('billTime', models.DateTimeField()),
                ('cardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerId', to='mainsys.user'),
        ),
        migrations.CreateModel(
            name='borrowLog',
            fields=[
                ('borrowId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrowTime', models.DateTimeField()),
                ('returnTime', models.DateTimeField(blank=True, null=True)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.book')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsys.user')),
            ],
        ),
    ]
