# Generated by Django 5.1.3 on 2024-11-08 06:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0003_alter_book_bookprice_alter_card_cardid'),
    ]

    operations = [
        migrations.CreateModel(
            name='good',
            fields=[
                ('goodId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goodName', models.CharField(max_length=50)),
                ('goodImgUrl', models.CharField(blank=True, max_length=300, null=True)),
                ('goodPrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('goodAmount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='goods',
        ),
        migrations.AddField(
            model_name='book',
            name='bookImgUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 8', regex='^.{10}$')]),
        ),
    ]
